### ISSUE TITLE
Relies on deprecated syntex crate

### ISSUE THREAD

**Issue by stouset** [gnzlbg/ctest#77] opened 2019-07-25 19:49 UTC
Syntex is deprecated and unmaintained and has been so for two years. Can we find an alternative?

**Comment by gnzlbg** [comment] 2019-07-26 08:41
> Can we find an alternative?

I don't know of any. The syntex crate was deprecated without providing a replacement. We maintain our own fork of `syntex` (syntex2) for that.

**Comment by gnzlbg** [comment] 2019-07-29 15:56
This is a duplicate of #70 .

**Closed by gnzlbg** 2019-07-29 15:56 UTC
