### ISSUE TITLE
Use of macros causes panic in syntex_syntax

### ISSUE THREAD

**Issue by Fraser999** [gnzlbg/ctest#23] opened 2017-10-20 14:17 UTC
Using a macro can cause [unreachable code in syntex_syntax](https://github.com/serde-rs/syntex/blob/rust/syntex_syntax/src/ext/expand.rs#L314) to get hit.  For example if you change [this test line](https://github.com/alexcrichton/ctest/blob/master/testcrate/src/t1.rs#L6) to:
```rust
pub const T1S: &'static str = stringify!(foo);
```
then the test panics.

**Comment by klingtnet** [comment] 2018-08-05 09:39
I can confirm this issue.

**Comment by gnzlbg** [comment] 2019-07-29 16:06
I don't think we are planning to fix this in any way, since this would require us to implement macro expansion in the syntex crate, which is deprecated. AFAICT there are no libraries that allow you to perform macro expansion in Rust from an AST, so i'm going to close this for now as "non actionable". 

Feel free to open issues upstream about how to solve this problem.

**Closed by gnzlbg** 2019-07-29 16:06 UTC
